package proposalrunner

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"orchv3/internal/commandrunner"
	"orchv3/internal/config"
)

func TestRunnerHappyPathCreatesPRAndCommentFromLastMessage(t *testing.T) {
	task := "Add project roadmap workflow"
	cfg := validConfig()
	tempDir := filepath.Join(t.TempDir(), "orchv3-run")
	cloneDir := filepath.Join(tempDir, "repo")
	lastMessagePath := filepath.Join(tempDir, lastMessageFile)
	fake := &fakeCommandRunner{
		responses: []fakeResponse{
			{},
			{
				stdout:           "codex stdout",
				stderr:           "codex stderr",
				writeLastMessage: true,
				lastMessage:      "\nFinal Codex response for PR comment.\n",
			},
			{stdout: "?? openspec/changes/add-project-roadmap-workflow/proposal.md\n"},
			{},
			{},
			{},
			{},
			{stdout: "https://github.com/example/project/pull/42\n"},
			{},
		},
	}
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	removeCalled := false

	runner := &Runner{
		Config:  cfg,
		Command: fake,
		Stdout:  &stdout,
		Stderr:  &stderr,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			return tempDir, nil
		},
		RemoveAll: func(path string) error {
			removeCalled = true
			return nil
		},
		Now: fixedTime,
	}

	prURL, err := runner.Run(context.Background(), task)
	if err != nil {
		t.Fatalf("Run() returned error: %v", err)
	}

	if prURL != "https://github.com/example/project/pull/42" {
		t.Fatalf("prURL = %q", prURL)
	}
	if removeCalled {
		t.Fatal("RemoveAll called with CleanupTemp=false")
	}

	assertCommand(t, fake.commands[0], "git", []string{"clone", cfg.RepositoryURL, cloneDir}, tempDir)
	assertCommand(t, fake.commands[1], "codex", []string{"exec", "--json", "--sandbox", "danger-full-access", "--output-last-message", lastMessagePath, "--cd", cloneDir, "-"}, cloneDir)
	if !strings.Contains(fake.commands[1].stdin, "openspec-propose") {
		t.Fatalf("codex stdin = %q, want openspec-propose instruction", fake.commands[1].stdin)
	}
	if !strings.Contains(fake.commands[1].stdin, task) {
		t.Fatalf("codex stdin = %q, want original task", fake.commands[1].stdin)
	}

	branchName := "codex/proposal/20260422100203-add-project-roadmap-workflow"
	assertCommand(t, fake.commands[2], "git", []string{"status", "--short"}, cloneDir)
	assertCommand(t, fake.commands[3], "git", []string{"checkout", "-b", branchName}, cloneDir)
	assertCommand(t, fake.commands[4], "git", []string{"add", "-A"}, cloneDir)
	assertCommand(t, fake.commands[5], "git", []string{"commit", "-m", "OpenSpec proposal: Add project roadmap workflow"}, cloneDir)
	assertCommand(t, fake.commands[6], "git", []string{"push", "-u", "origin", branchName}, cloneDir)
	assertCommand(t, fake.commands[7], "gh", []string{
		"pr", "create",
		"--base", "main",
		"--head", branchName,
		"--title", "OpenSpec proposal: Add project roadmap workflow",
		"--body", "Generated by orchv3 proposal runner.\n\nTask:\nAdd project roadmap workflow\n",
	}, cloneDir)
	assertCommand(t, fake.commands[8], "gh", []string{
		"pr", "comment", "https://github.com/example/project/pull/42",
		"--body", "Final Codex response for PR comment.",
	}, cloneDir)

	stdoutEvents := decodeLogEvents(t, stdout.String())
	assertLogMessage(t, stdoutEvents, "codex", "codex stdout")
	assertLogMessage(t, stdoutEvents, "git", "?? openspec/changes/add-project-roadmap-workflow/proposal.md")
	assertLogMessage(t, stdoutEvents, "github", "https://github.com/example/project/pull/42")
	assertLogMessage(t, stdoutEvents, "github", "created PR comment from final Codex response")

	stderrEvents := decodeLogEvents(t, stderr.String())
	assertLogMessage(t, stderrEvents, "codex", "codex stderr")
}

func TestRunnerRejectsEmptyDescriptionBeforeSideEffects(t *testing.T) {
	fake := &fakeCommandRunner{}
	mkdirCalled := false
	runner := &Runner{
		Config:  validConfig(),
		Command: fake,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			mkdirCalled = true
			return "", nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), " \n\t ")
	if err == nil {
		t.Fatal("Run() error = nil, want non-nil")
	}
	if mkdirCalled {
		t.Fatal("MkdirTemp called for empty task")
	}
	if len(fake.commands) != 0 {
		t.Fatalf("commands executed = %d, want 0", len(fake.commands))
	}
}

func TestRunnerReturnsConfigValidationErrorBeforeSideEffects(t *testing.T) {
	cfg := validConfig()
	cfg.RepositoryURL = ""
	fake := &fakeCommandRunner{}
	mkdirCalled := false
	runner := &Runner{
		Config:  cfg,
		Command: fake,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			mkdirCalled = true
			return "", nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), "Task")
	if err == nil {
		t.Fatal("Run() error = nil, want non-nil")
	}
	if !strings.Contains(err.Error(), "PROPOSAL_REPOSITORY_URL") {
		t.Fatalf("Run() error = %q, want repository context", err.Error())
	}
	if mkdirCalled || len(fake.commands) != 0 {
		t.Fatal("side effects happened before config validation")
	}
}

func TestRunnerReturnsGitCloneFailure(t *testing.T) {
	errBoom := errors.New("clone failed")
	err := runWithResponses(t, []fakeResponse{{err: errBoom}}, nil)
	if err == nil || !strings.Contains(err.Error(), "git clone") {
		t.Fatalf("Run() error = %v, want git clone context", err)
	}
}

func TestRunnerReturnsCodexFailure(t *testing.T) {
	errBoom := errors.New("codex failed")
	err := runWithResponses(t, []fakeResponse{{}, {err: errBoom}}, nil)
	if err == nil || !strings.Contains(err.Error(), "codex proposal") {
		t.Fatalf("Run() error = %v, want codex context", err)
	}
}

func TestRunnerLogsWorkflowFailureAsJSONError(t *testing.T) {
	errBoom := errors.New("clone failed")
	var stdout bytes.Buffer
	runner := &Runner{
		Config:  validConfig(),
		Command: &fakeCommandRunner{responses: []fakeResponse{{err: errBoom}}},
		Stdout:  &stdout,
		Stderr:  io.Discard,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			return "/tmp/orchv3-run", nil
		},
		RemoveAll: func(path string) error {
			return nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), "Task")
	if err == nil {
		t.Fatal("Run() error = nil, want non-nil")
	}

	events := decodeLogEvents(t, stdout.String())
	assertLogEvent(t, events, "proposalrunner", "error", "workflow failed: git clone")
}

func TestRunnerCommandOutputIsJSONOnly(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	err := runWithOutput(t, []fakeResponse{
		{},
		{stdout: "codex line 1\ncodex line 2", stderr: "codex warning"},
		{stdout: " M openspec/file.md\n"},
		{},
		{},
		{},
		{},
		{stdout: "https://github.com/example/project/pull/42\n"},
	}, &stdout, &stderr)
	if err != nil {
		t.Fatalf("Run() returned error: %v", err)
	}

	stdoutEvents := decodeLogEvents(t, stdout.String())
	assertLogMessage(t, stdoutEvents, "codex", "codex line 1")
	assertLogMessage(t, stdoutEvents, "codex", "codex line 2")
	assertLogMessage(t, stdoutEvents, "git", " M openspec/file.md")
	assertLogMessage(t, stdoutEvents, "github", "https://github.com/example/project/pull/42")

	stderrEvents := decodeLogEvents(t, stderr.String())
	assertLogMessage(t, stderrEvents, "codex", "codex warning")
}

func TestRunnerReturnsMissingChangesError(t *testing.T) {
	err := runWithResponses(t, []fakeResponse{{}, {}, {stdout: "\n"}}, nil)
	if err == nil || !strings.Contains(err.Error(), "no changes produced") {
		t.Fatalf("Run() error = %v, want missing changes context", err)
	}
}

func TestRunnerReturnsPRCreationFailure(t *testing.T) {
	errBoom := errors.New("gh auth missing")
	err := runWithResponses(t, []fakeResponse{
		{},
		{writeLastMessage: true, lastMessage: "Final response"},
		{stdout: " M openspec/file.md\n"},
		{},
		{},
		{},
		{},
		{err: errBoom},
	}, nil)
	if err == nil || !strings.Contains(err.Error(), "github pr create") {
		t.Fatalf("Run() error = %v, want PR creation context", err)
	}
}

func TestRunnerReturnsFinalResponseCommentFailure(t *testing.T) {
	errBoom := errors.New("comment failed")
	err := runWithTempDir(t, []fakeResponse{
		{},
		{writeLastMessage: true, lastMessage: "Final response"},
		{stdout: " M openspec/file.md\n"},
		{},
		{},
		{},
		{},
		{stdout: "https://github.com/example/project/pull/42\n"},
		{err: errBoom},
	}, io.Discard, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "github final response comment") {
		t.Fatalf("Run() error = %v, want comment context", err)
	}
}

func TestRunnerCleanupTempWhenConfigured(t *testing.T) {
	cfg := validConfig()
	cfg.CleanupTemp = true
	fake := &fakeCommandRunner{
		responses: []fakeResponse{
			{},
			{writeLastMessage: true, lastMessage: "Final response"},
			{stdout: " M openspec/file.md\n"},
			{},
			{},
			{},
			{},
			{stdout: "https://github.com/example/project/pull/42\n"},
			{},
		},
	}
	var removedPath string
	runner := &Runner{
		Config:  cfg,
		Command: fake,
		Stdout:  io.Discard,
		Stderr:  io.Discard,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			return "/tmp/orchv3-run", nil
		},
		RemoveAll: func(path string) error {
			removedPath = path
			return nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), "Task")
	if err != nil {
		t.Fatalf("Run() returned error: %v", err)
	}
	if removedPath != "/tmp/orchv3-run" {
		t.Fatalf("removedPath = %q, want temp dir", removedPath)
	}
}

func TestBuildHelpers(t *testing.T) {
	now := time.Date(2026, 4, 22, 10, 2, 3, 0, time.UTC)
	if got, want := BuildBranchName("feature/proposal/", "Hello, OpenSpec world!", now), "feature/proposal/20260422100203-hello-openspec-world"; got != want {
		t.Fatalf("BuildBranchName() = %q, want %q", got, want)
	}

	prompt := BuildCodexPrompt("Describe task")
	if !strings.Contains(prompt, "openspec-propose") || !strings.Contains(prompt, "Describe task") {
		t.Fatalf("BuildCodexPrompt() = %q", prompt)
	}

	if got, want := strings.Join(CodexArgs("/tmp/clone", "/tmp/last-message.txt"), " "), "exec --json --sandbox danger-full-access --output-last-message /tmp/last-message.txt --cd /tmp/clone -"; got != want {
		t.Fatalf("CodexArgs() = %q, want %q", got, want)
	}
}

func TestRunnerSkipsEmptyLastMessageComment(t *testing.T) {
	var stdout bytes.Buffer
	fake := &fakeCommandRunner{
		responses: []fakeResponse{
			{},
			{writeLastMessage: true, lastMessage: " \n\t "},
			{stdout: " M openspec/file.md\n"},
			{},
			{},
			{},
			{},
			{stdout: "https://github.com/example/project/pull/42\n"},
		},
	}
	err := runWithTempDir(t, fake.responses, &stdout, io.Discard)
	if err != nil {
		t.Fatalf("Run() returned error: %v", err)
	}

	events := decodeLogEvents(t, stdout.String())
	assertLogMessage(t, events, "github", "skipped PR comment: final Codex response is empty")
}

func TestReadLastCodexMessage(t *testing.T) {
	path := filepath.Join(t.TempDir(), "last-message.txt")
	writeFile(t, path, "\n final response \n")

	got, err := ReadLastCodexMessage(path)
	if err != nil {
		t.Fatalf("ReadLastCodexMessage() returned error: %v", err)
	}
	if got != "final response" {
		t.Fatalf("ReadLastCodexMessage() = %q, want %q", got, "final response")
	}

	missing, err := ReadLastCodexMessage(filepath.Join(t.TempDir(), "missing.txt"))
	if err != nil {
		t.Fatalf("ReadLastCodexMessage() missing file error = %v", err)
	}
	if missing != "" {
		t.Fatalf("ReadLastCodexMessage() missing file = %q, want empty string", missing)
	}
}

func TestParsePRURL(t *testing.T) {
	tests := []struct {
		name   string
		output string
		want   string
	}{
		{
			name:   "plain url",
			output: "https://github.com/example/project/pull/42\n",
			want:   "https://github.com/example/project/pull/42",
		},
		{
			name:   "json url",
			output: `{"url":"https://github.com/example/project/pull/42"}`,
			want:   "https://github.com/example/project/pull/42",
		},
		{
			name: "url in text",
			output: `Creating pull request for branch into main
https://github.com/example/project/pull/42`,
			want: "https://github.com/example/project/pull/42",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parsePRURL(tt.output)
			if err != nil {
				t.Fatalf("parsePRURL() returned error: %v", err)
			}
			if got != tt.want {
				t.Fatalf("parsePRURL() = %q, want %q", got, tt.want)
			}
		})
	}
}

func runWithResponses(t *testing.T, responses []fakeResponse, cfg *config.ProposalRunnerConfig) error {
	t.Helper()

	return runWithResponsesAndWriters(t, responses, cfg, io.Discard, io.Discard)
}

func runWithOutput(t *testing.T, responses []fakeResponse, stdout io.Writer, stderr io.Writer) error {
	t.Helper()

	return runWithResponsesAndWriters(t, responses, nil, stdout, stderr)
}

func runWithResponsesAndWriters(t *testing.T, responses []fakeResponse, cfg *config.ProposalRunnerConfig, stdout io.Writer, stderr io.Writer) error {
	t.Helper()

	useCfg := validConfig()
	if cfg != nil {
		useCfg = *cfg
	}

	runner := &Runner{
		Config:  useCfg,
		Command: &fakeCommandRunner{responses: responses},
		Stdout:  stdout,
		Stderr:  stderr,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			return "/tmp/orchv3-run", nil
		},
		RemoveAll: func(path string) error {
			return nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), "Task")
	return err
}

func runWithTempDir(t *testing.T, responses []fakeResponse, stdout io.Writer, stderr io.Writer) error {
	t.Helper()

	tempDir := filepath.Join(t.TempDir(), "orchv3-run")
	runner := &Runner{
		Config:  validConfig(),
		Command: &fakeCommandRunner{responses: responses},
		Stdout:  stdout,
		Stderr:  stderr,
		MkdirTemp: func(dir string, pattern string) (string, error) {
			return tempDir, nil
		},
		RemoveAll: func(path string) error {
			return nil
		},
		Now: fixedTime,
	}

	_, err := runner.Run(context.Background(), "Task")
	return err
}

func validConfig() config.ProposalRunnerConfig {
	return config.ProposalRunnerConfig{
		RepositoryURL: "git@github.com:example/project.git",
		BaseBranch:    "main",
		RemoteName:    "origin",
		BranchPrefix:  "codex/proposal",
		PRTitlePrefix: "OpenSpec proposal:",
		GitPath:       "git",
		CodexPath:     "codex",
		GHPath:        "gh",
	}
}

func fixedTime() time.Time {
	return time.Date(2026, 4, 22, 10, 2, 3, 0, time.UTC)
}

type fakeCommandRunner struct {
	commands  []recordedCommand
	responses []fakeResponse
}

type recordedCommand struct {
	name  string
	args  []string
	dir   string
	stdin string
}

type fakeResponse struct {
	stdout           string
	stderr           string
	err              error
	writeLastMessage bool
	lastMessage      string
}

func (runner *fakeCommandRunner) Run(ctx context.Context, command commandrunner.Command) error {
	stdin := ""
	if command.Stdin != nil {
		content, err := io.ReadAll(command.Stdin)
		if err != nil {
			return err
		}
		stdin = string(content)
	}

	runner.commands = append(runner.commands, recordedCommand{
		name:  command.Name,
		args:  append([]string(nil), command.Args...),
		dir:   command.Dir,
		stdin: stdin,
	})

	index := len(runner.commands) - 1
	if index >= len(runner.responses) {
		return nil
	}

	response := runner.responses[index]
	if response.writeLastMessage {
		lastMessagePath, ok := findArgValue(command.Args, "--output-last-message")
		if !ok {
			return errors.New("missing --output-last-message argument")
		}
		if err := os.MkdirAll(filepath.Dir(lastMessagePath), 0700); err != nil {
			return err
		}
		if err := os.WriteFile(lastMessagePath, []byte(response.lastMessage), 0600); err != nil {
			return err
		}
	}
	if response.stdout != "" && command.Stdout != nil {
		if _, err := io.WriteString(command.Stdout, response.stdout); err != nil {
			return err
		}
	}
	if response.stderr != "" && command.Stderr != nil {
		if _, err := io.WriteString(command.Stderr, response.stderr); err != nil {
			return err
		}
	}

	return response.err
}

func findArgValue(args []string, flag string) (string, bool) {
	for index := 0; index < len(args)-1; index++ {
		if args[index] == flag {
			return args[index+1], true
		}
	}

	return "", false
}

func assertCommand(t *testing.T, got recordedCommand, name string, args []string, dir string) {
	t.Helper()

	if got.name != name {
		t.Fatalf("command name = %q, want %q", got.name, name)
	}
	if !reflect.DeepEqual(got.args, args) {
		t.Fatalf("command args = %#v, want %#v", got.args, args)
	}
	if got.dir != dir {
		t.Fatalf("command dir = %q, want %q", got.dir, dir)
	}
}

func writeFile(t *testing.T, path string, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		t.Fatalf("create directory for %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

type logEvent struct {
	Module  string `json:"module"`
	Type    string `json:"type"`
	Message string `json:"message"`
}

func decodeLogEvents(t *testing.T, output string) []logEvent {
	t.Helper()

	lines := strings.Split(strings.TrimSpace(output), "\n")
	events := make([]logEvent, 0, len(lines))
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			continue
		}

		var event logEvent
		if err := json.Unmarshal([]byte(line), &event); err != nil {
			t.Fatalf("decode log event %q: %v", line, err)
		}
		events = append(events, event)
	}

	return events
}

func assertLogMessage(t *testing.T, events []logEvent, module string, message string) {
	t.Helper()

	assertLogEvent(t, events, module, "info", message)
}

func assertLogEvent(t *testing.T, events []logEvent, module string, logType string, message string) {
	t.Helper()

	for _, event := range events {
		if event.Module == module && event.Type == logType && strings.Contains(event.Message, message) {
			return
		}
	}

	t.Fatalf("missing log event module=%q type=%q message containing %q in %#v", module, logType, message, events)
}
