input {
  tcp {
    port  => 5000
    codec => json_lines
  }
}

filter {
  date {
    match        => ["time", "ISO8601"]
    target       => "@timestamp"
    remove_field => ["time"]
  }
  mutate {
    rename => { "type" => "level" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orchv3-%{+YYYY.MM.dd}"
  }
}
